### ISSUE TITLE
[MPOM-102] Upgrade to FindBugs Maven Plugin 3.0.3

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-parent#383]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[MPOM-102](https://issues.apache.org/jira/browse/MPOM-102?redirect=false)** and commented

The currently used version (2.5.5) does not properly work on Java 8:

```
[WARNING] javadoc: warning - Error fetching URL: http://junit.org/javadoc/4.10/
[INFO] Generating "FindBugs" report             --- findbugs-maven-plugin:2.5.5:findbugs
[INFO] Locale is en
[INFO] Fork Value is true
     [java] Jan 26, 2016 5:55:37 PM java.util.prefs.WindowsPreferences <init>
     [java] WARNUNG: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
     [java] The following errors occurred during analysis:
     [java]   Unable to get XClass for java/lang/StringBuilder
     [java]     java.lang.ArrayIndexOutOfBoundsException: 26721
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/String
     [java]     java.lang.ArrayIndexOutOfBoundsException: 26721
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/util/Map$Entry
     [java]     java.lang.ArrayIndexOutOfBoundsException: 9216
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/Class
     [java]     java.lang.ArrayIndexOutOfBoundsException
     [java]   Couldn't get class info for java/util/Map$Entry
     [java]     java.lang.ArrayIndexOutOfBoundsException: 9216
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 7352
     [java]     at org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]     at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]     at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]     at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]     at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]     at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.getXMethod(TypeQualifierNullnessAnnotationDatabase.java:363)
     [java]     at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.addMethodParameterAnnotation(TypeQualifierNullnessAnnotationDatabase.java:425)
     [java]     at edu.umd.cs.findbugs.ba.DefaultNullnessAnnotations.addDefaultNullnessAnnotations(DefaultNullnessAnnotations.java:69)
     [java]     at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.loadAuxiliaryAnnotations(TypeQualifierNullnessAnnotationDatabase.java:460)
     [java]     at edu.umd.cs.findbugs.ba.AnalysisContext.updateDatabases(AnalysisContext.java:962)
     [java]     at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1154)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:282)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.854 s
[INFO] Finished at: 2016-01-26T17:55:38+01:00
[INFO] Final Memory: 60M/827M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project maven-archiver: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.4:site failed: Java returned: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Running with 3.0.3 resolves the problem but requires Java 7 and Maven 3.0.1 for the plugin to run. This is just relevant when running `mvn site -Preporting`, a trade-off which can be accepted.

---

**Affects:** MAVEN-27

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [r1739527](http://svn.apache.org/r1739527).
