### ISSUE TITLE
[MPOM-204] Getting INSTANCE error while running maven build using POM

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-parent#424]
**[Jagan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erlajagan)** opened **[MPOM-204](https://issues.apache.org/jira/browse/MPOM-204?redirect=false)** and commented

Hi all, I created Maven project and and added Headless browser selenium script.

I created testNG suit for that script.

Also added required plugins and dependencies in POM.xml file.

But while running as maven build getting below error

```
 [RemoteTestNG] detected TestNG version 6.9.9
[TestNG] Running:
  C:\Users\IBM_ADMIN\git\JaganMavenPL\src\selenium\resources\testng.xml

Exception in thread "Thread-1" java.lang.NoSuchFieldError: INSTANCE
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
    at com.gargoylesoftware.htmlunit.HttpWebConnection.configureHttpsScheme(HttpWebConnection.java:625)
    at com.gargoylesoftware.htmlunit.HttpWebConnection.createHttpClient(HttpWebConnection.java:557)
    at com.gargoylesoftware.htmlunit.HttpWebConnection.getHttpClientBuilder(HttpWebConnection.java:518)
    at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:170)
    at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1397)
    at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1315)
    at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:394)
    at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:315)
    at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:683)
    at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$get$8(HtmlUnitDriver.java:670)
    at org.openqa.selenium.htmlunit.HtmlUnitDriver.lambda$runAsync$0(HtmlUnitDriver.java:424)
    at java.lang.Thread.run(Thread.java:748)
```

 

Could any one help on this how to resolve.

---

**Attachments:**
- [POM_Mavendependencies.docx](https://issues.apache.org/jira/secure/attachment/12933616/POM_Mavendependencies.docx) (_102.58 kB_)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

This means that you're using a different version of `org.apache.http.conn.ssl.SSLConnectionSocketFactory` then originally used by `HttpWebConnection`.
Maybe you have multiple versions of SSLConnectionSocketFactory on your classpath, or an older/newer version of the dependency containing this class (probably http-client).

**Comment by jira-importer** [comment]
**[Jagan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erlajagan)** commented

Hi Robert,

I added following versions in maven dependencies for http-client and core).

httpclient-4.5.2.jar

httpcore-4.4.4.jar

httpmime-4.5.jar

Please refer attached screen shot and suggest on this.

**Comment by jira-importer** [comment]
**[Jagan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=erlajagan)** commented

This is simple Selenium script I written using headless browser

package selenium.headlessbrowsertest;

import org.openqa.selenium.htmlunit.HtmlUnitDriver;
import org.testng.annotations.Test;

public class HBrowserMavenSeleniumtest {    
    `@Test`
    public void testUrl() throws InterruptedException {    
    HtmlUnitDriver driver=new HtmlUnitDriver();
    //WebDriver driver=new FirefoxDriver();
    driver.get("https://mvnrepository.com/");
    Thread.sleep(8000);
    System.out.println(driver.getTitle());
    Thread.sleep(2000);
    }    

}

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

htmlunit-2.18 was built with httpclient-4.5, httpmime-4.5 and httpcore-4.4.1 (see http://search.maven.org/#artifactdetails%7Cnet.sourceforge.htmlunit%7Chtmlunit%7C2.18%7Cjar )
You could also try the latest version of htmlunit, i.e. 2.32
